name: Main CI/CD

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: ycpss91255-docker/template/.github/workflows/build-worker.yaml@v0.10.2
    with:
      image_name: ros1_bridge
      build_runtime: true
      platforms: linux/amd64,linux/arm64
      test_tools_version: v0.10.1

  call-release:
    needs: call-docker-build
    if: startsWith(github.ref, 'refs/tags/')
    uses: ycpss91255-docker/template/.github/workflows/release-worker.yaml@v0.10.2
    with:
      archive_name_prefix: ros1_bridge
